# Generated by Django 5.2.1 on 2025-05-30 19:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PilatesGravity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clase',
            options={'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AlterField(
            model_name='clase',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10, verbose_name='Día de la semana'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='horario',
            field=models.TimeField(verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='tipo',
            field=models.CharField(choices=[('Reformer', 'Pilates Reformer'), ('Cadillac', 'Pilates Cadillac')], max_length=20, verbose_name='Tipo de clase'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(error_messages={'max_length': 'El apellido no puede tener más de 100 caracteres.', 'required': 'El apellido es obligatorio.'}, max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo_verificacion',
            field=models.CharField(error_messages={'invalid': 'El código debe tener exactamente 4 dígitos.', 'max_length': 'El código no puede tener más de 4 caracteres.', 'required': 'El código de verificación es obligatorio.'}, help_text='Código de 4 dígitos que se usará para validar modificaciones o cancelaciones. ¡ES IMPORTANTE QUE LO RECUERDES!', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'El código debe tener exactamente 4 dígitos.')], verbose_name='Código de verificación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, error_messages={'invalid': 'Ingresa una dirección de correo electrónico válida.'}, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(error_messages={'max_length': 'El nombre no puede tener más de 100 caracteres.', 'required': 'El nombre es obligatorio.'}, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(error_messages={'max_length': 'El teléfono no puede tener más de 20 caracteres.', 'required': 'El teléfono es obligatorio.'}, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PilatesGravity.clase', verbose_name='Clase'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PilatesGravity.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(verbose_name='Fecha del turno'),
        ),
    ]
