# Generated by Django 5.2.1 on 2025-05-31 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PilatesGravity', '0002_alter_clase_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=10, verbose_name='Cupo máximo'),
        ),
        migrations.AlterUniqueTogether(
            name='clase',
            unique_together={('tipo', 'dia', 'horario')},
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reserva', models.CharField(editable=False, max_length=10, unique=True)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reserva')),
                ('activa', models.BooleanField(default=True, verbose_name='Reserva activa')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PilatesGravity.clase', verbose_name='Clase')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PilatesGravity.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'unique_together': {('cliente', 'clase')},
            },
        ),
    ]
