# Generated by Django 5.2.1 on 2025-06-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PilatesGravity', '0003_clase_cupo_maximo_alter_clase_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clase',
            options={'ordering': ['dia', 'horario'], 'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_reserva'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
    ]
